### ISSUE TITLE
undefined reference to spooky

### ISSUE THREAD

**Issue by Julian52575** [Saturn345/Project-Yellow-Cap#1]
when I compile on Manjaro with all the dependency installed I get this error :
'''mips64-elf-ld: build/us/levels/bbh/leveldata.o:(.data+0x20234): undefined reference to `spooky_09005000' '''

**Comment by Saturn345** [comment]
oh umm yeah i made this a while ago and i was bad at decomp so thats why

**Comment by Saturn345** [comment]
just use the actual decomp

**Comment by Saturn345** [comment]
or if you are looking for beta hacks play b3313, tpp or idk
